/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Resource = {
  _type: "resource";
  type: "documentation" | "guide" | "repository" | "article" | "download";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon:
    | "layers"
    | "database"
    | "gauge"
    | "cloud"
    | "code"
    | "shield"
    | "zap"
    | "rocket"
    | "book-open"
    | "terminal"
    | "server"
    | "lock"
    | "workflow"
    | "sparkles"
    | "puzzle";
  title: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  notes?: BlockContent;
  keyPoints?: Array<string>;
  videoUrl: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  durationMinutes: number;
  freePreview?: boolean;
  studentCount?: number;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  instructor: InstructorReference;
  category: CategoryReference;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules: Array<
    {
      _key: string;
    } & Module
  >;
  price?: number;
  popular?: boolean;
  studentCount?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/sanity/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    popular,    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "durationMinutes": math::sum(modules[].lessons[]->durationMinutes)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level: "advanced" | "beginner" | "intermediate";
  popular: boolean | null;
  moduleCount: number;
  lessonCount: number;
  durationMinutes: number;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    price,    popular,    studentCount,    learningOutcomes[] { _key, icon, title, description },    instructor-> { _id, name, "slug": slug.current, photo, expertise },    category-> { _id, title, "slug": slug.current },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "durationMinutes": math::sum(modules[].lessons[]->durationMinutes),    modules[] {      _key,      title,      summary,      "durationMinutes": math::sum(lessons[]->durationMinutes),      "lessons": lessons[]-> { _id, title, "slug": slug.current, durationMinutes, freePreview }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level: "advanced" | "beginner" | "intermediate";
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "book-open"
      | "cloud"
      | "code"
      | "database"
      | "gauge"
      | "layers"
      | "lock"
      | "puzzle"
      | "rocket"
      | "server"
      | "shield"
      | "sparkles"
      | "terminal"
      | "workflow"
      | "zap";
    title: string;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    expertise: Array<string> | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number;
  lessonCount: number;
  durationMinutes: number;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    durationMinutes: number;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      durationMinutes: number;
      freePreview: boolean | null;
    }>;
  }>;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    notes,    keyPoints,    proTip,    resources[] { _key, type, title, description, url },    videoUrl,    thumbnail,    durationMinutes,    freePreview,    studentCount,    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc) [0] {      _id,      title,      "slug": slug.current,      coverImage,      level,      instructor-> { _id, name, "slug": slug.current, photo },      modules[] {        _key,        title,        "durationMinutes": math::sum(lessons[]->durationMinutes),        "lessons": lessons[]-> { _id, title, "slug": slug.current, durationMinutes }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  notes: BlockContent | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "documentation" | "download" | "guide" | "repository";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  videoUrl: string;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  durationMinutes: number;
  freePreview: boolean | null;
  studentCount: number | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    level: "advanced" | "beginner" | "intermediate";
    instructor: {
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    };
    modules: Array<{
      _key: string;
      title: string;
      durationMinutes: number;
      lessons: Array<{
        _id: string;
        title: string;
        slug: string;
        durationMinutes: number;
      }>;
    }>;
  } | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: SEARCH_LESSONS_QUERY
// Query: *[_type == "lesson" && _id in $ids] {    _id,    title,    "slug": slug.current,    summary,    keyPoints,    durationMinutes,    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc) [0] {      _id,      title,      "slug": slug.current,      coverImage,      modules[] { title, "lessonIds": lessons[]->_id }    }  }
export type SEARCH_LESSONS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  keyPoints: Array<string> | null;
  durationMinutes: number;
  course: {
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    modules: Array<{
      title: string;
      lessonIds: Array<string>;
    }>;
  } | null;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    photo,    expertise,    bio,    "courses": *[_type == "course" && references(^._id) && defined(slug.current)] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      coverImage,      level,      popular,      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[]),      "durationMinutes": math::sum(modules[].lessons[]->durationMinutes)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  expertise: Array<string> | null;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    level: "advanced" | "beginner" | "intermediate";
    popular: boolean | null;
    moduleCount: number;
    lessonCount: number;
    durationMinutes: number;
  }>;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courseCount: number;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] { "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] { "slug": slug.current }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] { "slug": slug.current }
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    popular,\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "durationMinutes": math::sum(modules[].lessons[]->durationMinutes)\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    learningOutcomes[] { _key, icon, title, description },\n    instructor-> { _id, name, "slug": slug.current, photo, expertise },\n    category-> { _id, title, "slug": slug.current },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "durationMinutes": math::sum(modules[].lessons[]->durationMinutes),\n    modules[] {\n      _key,\n      title,\n      summary,\n      "durationMinutes": math::sum(lessons[]->durationMinutes),\n      "lessons": lessons[]-> { _id, title, "slug": slug.current, durationMinutes, freePreview }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    notes,\n    keyPoints,\n    proTip,\n    resources[] { _key, type, title, description, url },\n    videoUrl,\n    thumbnail,\n    durationMinutes,\n    freePreview,\n    studentCount,\n    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc) [0] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage,\n      level,\n      instructor-> { _id, name, "slug": slug.current, photo },\n      modules[] {\n        _key,\n        title,\n        "durationMinutes": math::sum(lessons[]->durationMinutes),\n        "lessons": lessons[]-> { _id, title, "slug": slug.current, durationMinutes }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && _id in $ids] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    keyPoints,\n    durationMinutes,\n    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc) [0] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage,\n      modules[] { title, "lessonIds": lessons[]->_id }\n    }\n  }\n': SEARCH_LESSONS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    photo,\n    expertise,\n    bio,\n    "courses": *[_type == "course" && references(^._id) && defined(slug.current)] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      coverImage,\n      level,\n      popular,\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[]),\n      "durationMinutes": math::sum(modules[].lessons[]->durationMinutes)\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courseCount": count(*[_type == "course" && references(^._id)])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] { "slug": slug.current }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)] { "slug": slug.current }\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] { "slug": slug.current }\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
  }
}
